[project]
name = "control-plane-phone-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "hume[microphone]>=0.13.4",
  "python-dotenv>=1.0.1",
  "websockets>=12.0",
]
