# reference:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

name: Dependabot auto-merge

on:
  pull_request:
    types: ['opened', 'reopened', 'ready_for_review', 'synchronize']

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest

    # only runs if PR is opened by "dependabot[bot]"
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.HUME_BOT_TOKEN }}'

      - name: Approve a PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.HUME_BOT_TOKEN}}
        run: gh pr review --approve "$PR_URL"

      - name: Enable auto-merge for Dependabot PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.HUME_BOT_TOKEN}}
        run: gh pr merge --auto --squash "$PR_URL"
